<?php

return [
    'Aberdeen City',
    'Aberdeenshire',
    'Angus',
    'Argyll and Bute',
    'Clackmannanshire',
    'Dumfries and Galloway',
    'Dundee City',
    'East Ayrshire',
    'East Dunbartonshire',
    'East Lothian',
    'East Renfrewshire',
    'City of Edinburgh',
    'Falkirk',
    'Fife',
    'Glasgow City',
    'Highland',
    'Inverclyde',
    'Midlothian',
    'Moray',
    'Na h-Eileanan an Iar',
    'North Ayrshire',
    'North Lanarkshire',
    'Orkney Islands',
    'Perth and Kinross',
    'Renfrewshire',
    'Scottish Borders',
    'Shetland Islands',
    'South Ayrshire',
    'South Lanarkshire',
    'Stirling',
    'West Dunbartonshire',
    'West Lothian',
];
